version: "3.9"
services:
  linkedinagent:
    build: .
    links:
      - linkedinmongo
    env_file:
      - .env
  linkedinmongo:
    image: mongo
    ports:
      - "27017:27017"
    environment:
      - MONGO_INITDB_ROOT_USERNAME=****
      - MONGO_INITDB_ROOT_PASSWORD=****
    volumes:
      - mongo_data:/data/db
volumes:
  mongo_data: